### ISSUE TITLE
Dashboard 조회 API 구현

### ISSUE THREAD

**Issue by gomster96** [gomster96/LearnTube#30]
### Description
- Dashboard page 에서 정보들을 조회하는 API 들을 구현한다.

### Todo
- [x] 수강 중인 강의실 조회
- [x] 관리 중인 강의실 조회
- [x] 종료 된 강의실 조회

### ETC
