### ISSUE TITLE
구현된 API 기능 수정 

### ISSUE THREAD

**Issue by gomster96** [gomster96/LearnTube#45]
### Description
- 회의 후 이미 구현된 API 들 중 수정되어야할 필요가 있는 API 기능을 수정한다.

### Todo
- [x] classRoom 조회 API takeNum 까지 받아오기 
- [x] lecture create 될때 lectureNum이 자동으로 증가되도록 구현하기
- [x] 학생의 수강 반려 API들의 기능을 사실상 학생 수강신청 삭제로 변경
- [x] 공지 조회 API 최신순으로 정렬하기 
### ETC
